### ISSUE TITLE
Whats the format of athlete/affiliate.json

### ISSUE THREAD

**Issue by molinto** [bobross419/cf_scraper#1]
Hi, whats the format of athlete/affiliate.json files please?

Just trying to get my head around the pysonDB syntax

**Comment by bobross419** [comment]
@molinto I was able to scrounge up the files I had, but it looks like I never got around to populating affiliate.  The solution I have here doesn't scale well and it was taking days to pull in all the athletes.  I've pushed a partially populated athletes.json that I was using as well as what I have locally for affiliate.json, but the latter is just an empty data array.  Hope it helps.
